name: whiskers

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run_non_color_overrides:
    uses: catppuccin/actions/.github/workflows/whiskers-check.yml@v1
    with:
      args: templates/non_color_overrides.tera
    secrets: inherit
  run:
    uses: catppuccin/actions/.github/workflows/whiskers-check.yml@v1
    with:
      args: templates/wofi.tera
    secrets: inherit
